### ISSUE TITLE
bug 自定义文本黑名单

### ISSUE THREAD

**Issue by fffzzl** [gnuf0rce/Mirai-AntiPorn-Plugin#2]
自定义文本黑名单在百度api里返回正确，但是在插件里却会报错``
[bawDemo.txt](https://github.com/gnuf0rce/mirai-content-censor/files/8001006/bawDemo.txt)

报错代码上方
估计是没有写返回？

**Comment by fffzzl** [comment]
色情图片 报错
[图片报错.txt](https://github.com/gnuf0rce/mirai-content-censor/files/8001108/default.txt)

**Comment by cssxsh** [comment]
数据 解析错误

**Comment by cssxsh** [comment]
with https://github.com/gnuf0rce/mirai-content-censor/releases/tag/v1.2.2
尝试修复
