### ISSUE TITLE
消息误撤回

### ISSUE THREAD

**Issue by su-liu-guang** [gnuf0rce/Mirai-AntiPorn-Plugin#5]
不支持的消息显示为“[不支持的消息#-475816636][酸Q]” " [不支持的消息#1970352265]你的QQ暂不支持查看视频短片，请期待后续版本"，被识别为恶意推广然后撤回，目前可以通过白名单防止误撤
![image](https://github.com/gnuf0rce/mirai-content-censor/assets/104332832/98454971-a188-4f6e-8b0e-4f0b1da4f88a)
![image](https://github.com/gnuf0rce/mirai-content-censor/assets/104332832/26d545dd-988b-4185-9421-f1ecdf348a10)
![image](https://github.com/gnuf0rce/mirai-content-censor/assets/104332832/ca938d1b-c48c-4473-85f9-2e85718717f7)

**Comment by cssxsh** [comment]
https://github.com/gnuf0rce/mirai-content-censor/commit/18edf33623e5116e991a471a43bf8f1e3159897a

这个之前修过了

你找一下 ci 下载吧

**Comment by cssxsh** [comment]
https://github.com/gnuf0rce/mirai-content-censor/actions/runs/5578848313

**Comment by su-liu-guang** [comment]
好了，谢谢大佬
