### ISSUE TITLE
[Bug] `@群成员` 内容被传递为 QQ 号，导致正常信息误判为恶意推广

### ISSUE THREAD

**Issue by Takeoff0518** [gnuf0rce/Mirai-AntiPorn-Plugin#6]
插件版本：[v1.3.10](https://github.com/gnuf0rce/mirai-content-censor/releases/tag/v1.3.10)

如图，`@群成员` 内容被传递为 QQ 号，导致正常信息误判为恶意推广，触发了撤回，与 #5 的情况类似。

希望在调用时直接忽略 `@群成员` 的内容。

![QQ截图20230825215526](https://github.com/gnuf0rce/mirai-content-censor/assets/64719447/6aeed0b1-be75-4a43-9941-56ceb9da4259)

PS: 百度的自定义文本白名单好像并没有正则匹配的功能。

**Comment by cssxsh** [comment]
是否已尝试 #5  中提到的 dev 版本

**Comment by Takeoff0518** [comment]
已尝试最新的 CI 版本，已修复，当时以为只能修复类型超级表情的“不支持的消息类型”，谢谢大佬！
