### ISSUE TITLE
希望加个策略热更新

### ISSUE THREAD

**Issue by KiraIzumiSagiri** [gnuf0rce/Mirai-AntiPorn-Plugin#8]
大佬还有在维护吗，可以搞一个策略的热更新吗，或者手动刷新当前策略吗，每次改完都要重启一下bot，有点容易风控呀

**Comment by KiraIzumiSagiri** [comment]
如果可以，能再加个撤回消息后的自定义文本就好了，或者就是关掉撤回提醒

**Comment by cssxsh** [comment]
最近有点忙，会迟一些处理

**Comment by cssxsh** [comment]
你说的 `策略` 是指什么东西
这个插件貌似没有你说的功能

**Comment by cssxsh** [comment]
我猜你是需要热更新 `设置>审核内容 (config/io.github.gnuf0rce.content-censor/ContentCensor.yml)`
