### ISSUE TITLE
插件能否设置作用域

### ISSUE THREAD

**Issue by WetlWang0625** [gnuf0rce/Mirai-AntiPorn-Plugin#9]
这个插件加入后是对所有的群生效么，能否加入作用域控制，来设置仅针对某个群生效。或者说目前只能通过对群添加权限来让某个群所有成员免检来避免生效。

**Comment by cssxsh** [comment]
1. 需要 群主/管理员 身份才会工作
2. 拥有权限 `io.github.gnuf0rce.content-censor:no-censor` 的用户将不会被检测
